name: calin.fabri
favicon: null
layout_spectrum: 0.9062686203978956
typography_spectrum: 0.30496013979427516
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5473926167469472
  lightness: 0.3330923879984766
  saturation: 0.598496560472995
  rhythmicContrast: 0.4008459902834147
purpose: []
